name: ASP.NET Core Action For Azure Web App Deployment

on: 
  push:
    banches:
      - 'master'

    paths-ignore:
      - 'README*'
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  publish-test-coverage-deploy:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100

    - name: Build with dotnet
      run: dotnet publish -c Release -r linux-x64 -o myapp
      
    - name: Test with coverage
      working-directory: ./tests
      run: dotnet test /p:CollectCoverage=true

    # deploy to azure app service
    - name: Deploy to Azure
      uses: azure/webapps-deploy@master
      with:
        app-name: ${{ secrets.azureWebAppName }}
        publish-profile: ${{ secrets.azureWebAppPP }}
        package: './myapp'
